version: "3.8"

services:
  # Banco de dados PostgreSQL 15
  db:
    image: postgres:15
    container_name: financial-planner-db
    environment:
      POSTGRES_USER: planner
      POSTGRES_PASSWORD: plannerpw
      POSTGRES_DB: plannerdb
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U planner -d plannerdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API (Node.js 20 + Fastify 4)
  backend:
    build:
      context: ./financial-planner-backend
      dockerfile: Dockerfile
    container_name: financial-planner-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://planner:plannerpw@db:5432/plannerdb
      NODE_ENV: production
      PORT: 3001
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Frontend (Next.js 14)
  frontend:
    build:
      context: ./financial-planner-frontend
      dockerfile: Dockerfile
    container_name: financial-planner-frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    restart: unless-stopped

volumes:
  pg_data:
    driver: local
