version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: planner
      POSTGRES_PASSWORD: plannerpw
      POSTGRES_DB: plannerdb
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./financial-planner-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://planner:plannerpw@db:5432/plannerdb
    ports:
      - "3001:3001"
    # Observação: o serviço backend deve expor um servidor Fastify na porta 3001.
    # Espera-se que exista em financial-planner-backend:
    # - src/server.ts que cria o app Fastify e chama app.listen({ port: 3001 })
    # - rota de health: GET /health (retorna { status: 'ok' })
    # - plugin @fastify/swagger registrado em /documentation
    # Ajuste o comando (command) se usar outro script de start (ex: pnpm/npm).

  frontend:
    build:
      context: ./financial-planner-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3001

volumes:
  pg_data:
