name: CI/CD Pipeline

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main]

jobs:
    # Job para análise do backend
    backend-analysis:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./financial-planner-backend

        steps:
            - name: Checkout código
              uses: actions/checkout@v4

            - name: Configurar Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
                  cache-dependency-path: financial-planner-backend/package-lock.json

            - name: Instalar dependências
              run: npm ci --legacy-peer-deps

            - name: Executar linting
              run: npm run lint

            - name: Executar testes
              run: npm run test:ci

            - name: Gerar relatório de cobertura
              run: npm run test:coverage

            - name: Upload cobertura para SonarCloud
              uses: sonarcloud-github-action@master
              with:
                  projectKey: financial-planner-case
                   organization: financial-planner-org
                  token: ${{ secrets.SONAR_TOKEN }}

    # Job para análise do frontend
    frontend-analysis:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./financial-planner-frontend

        steps:
            - name: Checkout código
              uses: actions/checkout@v4

            - name: Configurar Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
                  cache-dependency-path: financial-planner-frontend/package-lock.json

            - name: Instalar dependências
              run: npm ci

            - name: Executar linting
              run: npm run lint

            - name: Executar build
              run: npm run build

            - name: Executar testes E2E
              run: npm run test:e2e

            - name: Upload cobertura para SonarCloud
              uses: sonarcloud-github-action@master
              with:
                  projectKey: financial-planner-case
                   organization: financial-planner-org
                  token: ${{ secrets.SONAR_TOKEN }}

    # Job para build e deploy
    build-and-deploy:
        runs-on: ubuntu-latest
        needs: [backend-analysis, frontend-analysis]
        if: github.ref == 'refs/heads/main'

        steps:
            - name: Checkout código
              uses: actions/checkout@v4

            - name: Configurar Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Fazer login no Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build e push das imagens
              run: |
                  docker-compose build
                  docker-compose push
